### PR TITLE
Added string() to role so that I can use it in slash commands

### PR DESCRIPTION
**Pull request by djpiper28**

### CODE REVIEW

**Review by szerookii — APPROVED** [review]
Can you document this function for doc gen ?

**Review by szerookii — CHANGES_REQUESTED** [review]
Can you document this function for doc gen ?

**Review by szerookii — APPROVED** [review]

**Comment by szerookii** [comment]
Thank you for contributing to Goscord.

**Comment by djpiper28** [comment]
> Thank you for contributing to Goscord.

Cheers gov.

**Pull request merged**
